### PR TITLE
added (generic) repeat function to be used in vscode script

### PR DESCRIPTION
**Pull request by christianhultin**

### CODE REVIEW

**Comment by dwiel** [comment]
@christianhultin it looks like there are some merge conflicts now

**Comment by christianhultin** [comment]
@dwiel how so? from my and it only says "This branch has no conflicts with the base branch", or am i missing something?

**Comment by christianhultin** [comment]
merge latest with master, hope that helps

**Comment by dwiel** [comment]
Merged thanks

**Pull request merged**
