### PR TITLE
Split std into multiple files

### PR DESCRIPTION
**Pull request by dylan-chong**
Partial refactoring for #39

### CODE REVIEW

**Comment by wizonesolutions** [comment]
Probably title_case_capitalize_word (US spelling for consistency)

**Comment by dylan-chong** [comment]
Getting there! Only 47 commands left in STD.py!  will be another few days before a finish.  anyone, let me know if you want to merge early  so that the parts I have moved around can be refactored  earlier

**Comment by dylan-chong** [comment]
Okay have done plenty of stuff, but there is plenty of stuff to move out of STD – I don't think I'll ever finish, so might as well get what I have merged now, so we can start parallel refactoring.

I have tried to mostly avoid doing any opinionated changes to the grammar, and just making breaking changes in general, although I did remove a few commands like `"swick": Key("cmd-tab"),` and `state import/goto/class` because they can be said with `word import` and `goto` isnt commonly used.

Everything else is just moving stuff from the STD file into new files, and trying to remove commands with other files, which you will see as the random changes to other files.

**Comment by dwiel** [comment]
Nice work! It has been much needed for a while now

**Pull request merged**
