### PR TITLE
improve formatting and surrounder commands

### PR DESCRIPTION
**Pull request by g-sam**
- allow for ( a | b ) syntax in formatter list
- keep surrounder commands in one place
- create cmd + dgndictation and cmd + cmd variants of ~all formatters~ (EDIT: surrounders)
- allow formatting of highlighted words when a cmd + cmd variant exists

### CODE REVIEW

**Comment by g-sam** [comment]
You might want to actually test this before merging as the whole thing is quite complicated and there could be regressions.

**Comment by g-sam** [comment]
hm, for example, I think I forgot to cater for cmds with more than one word (dickt in it)

**Comment by g-sam** [comment]
I don't think there's a sufficiently easy way to cater for multiword formatting commands given the structure of FormatText. I would be inclined to delete them and let people add them separately if desired. Thoughts?

**Comment by zach-nervana** [comment]
something as complex as these formatters would probably benefit from some unit tests. If we make a function which maps from `words` -> `formatted text`, unit tests shouldn't be too hard.

**Comment by g-sam** [comment]
I agree, however, I'm personally a little reluctant to spend time writing unit tests when the api is unstable. I'd love it if someone else wrote tests but I'd rather fix a problem as I discover it atm.

**Comment by zach-nervana** [comment]
yeah makes sense, I haven't found the time either

**Comment by zach-nervana** [comment]
so you think this is ready for me to test drive or were you going to do more first?

**Comment by g-sam** [comment]
yeah, just stick to one word formatter commands if you agree I'll delete the others. (dickt in it is a bit risque for an office situation anyhow!)

**Comment by zach-nervana** [comment]
haha, yeah sounds good

**Comment by dwiel** [comment]
Ready for merge?

**Comment by g-sam** [comment]
from my side, yes!

**Pull request merged**
