### PR TITLE
fix basic_keys, add linting and formatting hooks, tidy symbols

### PR DESCRIPTION
**Pull request by g-sam**
fixes an issue introduced by the last pr (invalid optional syntax in context list) and blackens

### CODE REVIEW

**Comment by g-sam** [comment]
I have added linting config for circle CI. It seems to be working on my fork. I can't set it up for this project on the circle ci side though without some permissions.

**Comment by g-sam** [comment]
have added lint and formatting on a precommit hook and fixed all errors

**Comment by g-sam** [comment]
Just gonna keep pushing to this branch. Shouldn't be too confusing if you look commit-by-commit.

**Comment by dwiel** [comment]
Went through it all and looks good. You want me to wait to rebase and merge?

**Comment by g-sam** [comment]
It has been rebased: you can merge whenever

**Pull request merged**
